sudo: false

language: php

env:
  global:
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env:
        - DB=MYSQL PHPCS_TEST=1
    - php: 7.1
      env:
        - DB=MYSQL
    - php: 7.2
      env:
        - DB=MYSQL

before_script:
  # Init PHP
  - pecl install msgpack || true
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Composer Deps
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit test/unit
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src test; fi

branches:
  only:
    - master
