# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=4.0.x-dev
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env:
        - DB=MYSQL
    - php: 7.1
      env:
        - DB=MYSQL
    - php: 7.2
      env:
        - DB=MYSQL

before_script:
  # Init PHP
  - pecl install msgpack
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  
  # Composer Deps
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit --testsuite verifiable

branches:
  only: 
    - master
