---
Name: verifiable-config
---

SilverStripe\Core\Injector\Injector:
  BackendService:
    factory: PhpTek\Verifiable\Backend\BackendServiceFactory
  VizService:
    factory: PhpTek\Verifiable\Viz\HashVizFactory

PhpTek\Verifiable\Extension\VerifiableExtension:
  dependencies:
    service: '%$BackendService'
    
PhpTek\Verifiable\Control\VerifiableAdminController:
  dependencies:
    service: '%$BackendService'
    visualiser: '%$VizService'
    
PhpTek\Verifiable\Control\UpdateProofController:
  dependencies:
    service: '%$BackendService'
    
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'vendor/phptek/verifiable/client/dist/css/verifiable.css'
  extra_requirements_javascript:
    - 'vendor/phptek/verifiable/client/dist/js/verifiable.js'

SilverStripe\Assets\File:
  allowed_extensions:
    - svg
