---
Name: verifiable-config
---

SilverStripe\Core\Injector\Injector:
  BackendService:
    factory: PhpTek\Verifiable\Backend\BackendServiceFactory

PhpTek\Verifiable\Model\VerifiableExtension:
  dependencies:
    service: '%$BackendService'
    
PhpTek\Verifiable\Controller\VerifiableAdminController:
  dependencies:
    service: '%$BackendService'
    
PhpTek\Verifiable\Controller\UpdateProofController:
  dependencies:
    service: '%$BackendService'
    
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'vendor/phptek/verifiable/client/dist/css/verifiable.css'
  extra_requirements_javascript:
    - 'vendor/phptek/verifiable/client/dist/js/verifiable.js'

SilverStripe\Assets\File:
  allowed_extensions:
    - svg
