---
Name: verifiable-config
---

PhpTek\Verifiable\VerifiableDataExtension:
  dependencies:
    verifiableService: '%$PhpTek\Verify\Verifiable'

PhpTek\Verifiable\Verifiable:
  # One of: "trillian" or "chainpoint"
  backend: chainpoint
    