---
Name: verifiable-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    verifiable//$Action/$ClassName/$ModelID/$VersionID: 'PhpTek\Verifiable\Controller\VerifiableController'