---
Name: verifiable-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    'verifiable/tools/update': 'PhpTek\Verifiable\Control\UpdateProofController'
    'verifiable//$Action/$ClassName/$ModelID/$VersionID': 'PhpTek\Verifiable\Control\VerifiableAdminController'